
default: &default
  adapter: mysql2
  # encoding: unicode
  pool: 5

development:
  <<: *default
  database: empower
  username: empowercard
  password: 3mp0w3rc4rd
  host: empower.cvv9rfc5dwv5.ap-southeast-1.rds.amazonaws.com
  port: 3306

test:
  #<<: *default
  #database: Empower_test


production:
  <<: *default
  database: empower
  username: empowercard
  password: 3mp0w3rc4rd
  host: empower.cvv9rfc5dwv5.ap-southeast-1.rds.amazonaws.com
  port: 3306
